name = "OIF Device"
client_id = "oif-device"
schema_path = "./oc2/schemas"
schema_file = "hunt-ap-12-02-2023.json"
# schema_file = "th_ap_vbeta.json"
# schema_file = "slpf_ap_v2.0.json"

[HTTP]
is_enabled = true
host = "127.0.0.1"
port = 5000
log_Level="info"


[MQTT]
is_enabled = true
protocol = "MQTTv5"
# protocol = "MQTTv311"

transport = "tcp"
# transport = "websockets"

# broker = "localhost"
# broker="mosquitto.olympus.mtn" 
broker="3271a3ddd2eb43caa7c4b195c7d6cabd.s2.eu.hivemq.cloud"
# broker = "test.mosquitto.org" 

port = 8883
# port = 1883

username = 'Cav01'
password = 'Tango01Village'

# oc2/cmd/device/<ownDeviceID>
# oc2/cmd/ap/<topic for every profile the consumer supports>
# listen_topics = ["oc2/cmd/all","oc2/cmd/ap/hunt","oc2/cmd/ap/slpf", "oc2/cmd/device/th"]
listen_topics = ["oc2/cmd/device/th"]
resp_topics = ["oc2/rsp"]


[KESTREL]
is_enabled = true
is_sample_data = true
datasources = ["elastic", "file", "uri"]
huntbook_paths = ["./hunts/huntflow/"]