version: '3'

volumes:
  etcd:
    labels:
      com.screaming_bunny.container: 'Etcd'
      com.screaming_bunny.description: 'Persistent Etcd Volume'

  queue:
    labels:
      com.screaming_bunny.container: 'RabbitMQ'
      com.screaming_bunny.description: 'Persistent RabbitMQ Volume'

services:
  transport-coap:
    hostname: transport-coap
    image: g2inc/oif-device-transport-coap
    build:
      context: ./device/transport/coap
      dockerfile: Dockerfile
    env_file:
      - ./environment/queue.connect.env
    external_links:
      - queue
    ports:
      - 5682:5682/udp
    depends_on:
      - queue

  transport-http:
    hostname: transport-http
    image:  g2inc/oif-device-transport-http
    build:
      context: ./device/transport/http
    env_file:
      - ./environment/queue.connect.env
    external_links:
      - queue
    ports:
      - 5000:5001
    depends_on:
      - queue

  transport-https:
    hostname: transport-https
    image:  g2inc/oif-device-transport-https
    build:
      context: ./device/transport/https
    env_file:
      - ./environment/queue.connect.env
    external_links:
      - queue
    ports:
      - 5001:5001
    depends_on:
      - queue

  transport-mqtt:
    hostname: transport-mqtt
    image: g2inc/oif-device-transport-mqtt
    build:
      context: ./device/transport/mqtt
    env_file:
      - ./environment/queue.connect.env
      - ./environment/etcd.connect.env
      - ./environment/mqtt_transport.env
    external_links:
      - etcd
      - queue
    depends_on:
      - etcd
      - queue

#  transport-zmq:
#    hostname: transport-zmq
#    image: gitlab.ad.tsdcloudprojects.com:5005/screamingbunny/orchestrator/transport/zmq
#    env_file:
#      - ./environment/queue.connect.env
#      - ./environment/etcd.connect.env
#      - ./environment/zmq_transport.env
#    external_links:
#      - etcd
#      - queue
#    depends_on:
#      - etcd
#      - queue

  actuator-base:
    hostname: actuator-base
    image:  g2inc/oif-device-actutator-base
    build:
      context: ./device/actuator/base
    env_file:
      - ./environment/queue.connect.env
      - ./environment/etcd.connect.env
    external_links:
      - etcd
      - queue
    depends_on:
      - etcd
      - queue
    restart: on-failure:5

  actuator-slpf:
    hostname: actuator-slpf
    image:  g2inc/oif-device-actutator-slpf
    build:
      context: ./device/actuator/slpf
    env_file:
      - ./environment/queue.connect.env
      - ./environment/etcd.connect.env
    external_links:
      - etcd
      - queue
    depends_on:
      - etcd
      - queue
    restart: on-failure:5

  queue:
    hostname: rabbit
    image: rabbitmq:management-alpine
    ports:
      - 15672:15672
    command: sh -c "rabbitmq-plugins enable rabbitmq_mqtt; docker-entrypoint.sh rabbitmq-server"
    volumes:
      - queue:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:15672']
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure:5

  etcd:
    hostname: etcd
    image: quay.io/coreos/etcd:v3.3.25
    environment:
      ALLOW_NONE_AUTHENTICATION: 'yes'
      ETCD_DATA_DIR: '/data/etcd'
    ports:
      - 2380:2380
      - 2379:2379
    volumes:
      - etcd:/data/etcd
    command: sh -c 'etcd -listen-client-urls http://0.0.0.0:2379 -advertise-client-urls http://etcd:2379'
    restart: on-failure:5