version: '3'
# This in not a valid docker-compose file by itself!!
# Use this with the device-compose
# Ex) 'docker-compose ... -f device-compose.yaml -f device-compose.yaml ...'

volumes:
  logger:
    labels:
      com.screaming_bunny.container: 'ES Logger'
      com.screaming_bunny.description: 'Persistent Log Data Volume'

services:
  transport-mqtt:
    logging:
      driver: syslog
      options:
        syslog-address: 'udp://127.0.0.1:${LOG_PORT:-514}'
        syslog-format: rfc5424
        tag: "transport-mqtt"

  transport-https:
    logging:
      driver: syslog
      options:
        syslog-address: 'udp://127.0.0.1:${LOG_PORT:-514}'
        syslog-format: rfc5424
        tag: "transport-https"

  transport-coap:
    logging:
      driver: syslog
      options:
        syslog-address: 'udp://127.0.0.1:${LOG_PORT:-514}'
        syslog-format: rfc5424
        tag: "transport-coap"

  queue:
    logging:
      driver: syslog
      options:
        syslog-address: 'udp://127.0.0.1:${LOG_PORT:-514}'
        syslog-format: rfc5424
        tag: "buffer"

  actuator-slpf:
    logging:
      driver: syslog
      options:
        syslog-address: 'udp://127.0.0.1:${LOG_PORT:-514}'
        syslog-format: rfc5424
        tag: "actuator_slpf"

  logger_server:
    hostname: logger_server
    image: g2inc/oif-logger:server
    build:
      context: ./logger/server
      dockerfile: Dockerfile
    environment:
      ES_HOST: logger_elastic
      ES_PORT: 9200
      LOG_PREFIX: 'device'
      HOST_PORT: ${LOG_PORT:-514}
    ports:
      - 127.0.0.1:${LOG_PORT:-514}:514/udp
    volumes:
      - ./logs:/var/log/syslog
    external_links:
      - logger_elastic
    restart: on-failure:5

  logger_gui:
    hostname: logger_gui
    image: g2inc/oif-logger:gui
    build:
      context: ./logger/gui
      dockerfile: Dockerfile
    environment:
      ES_HOST: logger_elastic
      ES_PORT: 9200
    ports:
      - 8081:80
    external_links:
      - logger_elastic
    depends_on:
      - logger_server
    logging:
      driver: syslog
      options:
        syslog-address: 'udp://127.0.0.1:${LOG_PORT:-514}'
        syslog-format: rfc5424
        tag: "logger-gui"
    restart: on-failure:5

  logger_elastic:
    hostname: logger_elastic
    image: elasticsearch:7.5.1
    env_file:
      - ./environment/elastic.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - logger:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    depends_on:
      - logger_server
    logging:
      driver: syslog
      options:
        syslog-address: 'udp://127.0.0.1:${LOG_PORT:-514}'
        syslog-format: rfc5424
        tag: "logger-es"