version: '3'

volumes:
  etcd:
    labels:
      com.screaming_bunny.container: 'Etcd'
      com.screaming_bunny.description: 'Persistent Etcd Volume'

  queue:
    labels:
      com.screaming_bunny.container: 'RabbitMQ'
      com.screaming_bunny.description: 'Persistent RabbitMQ Volume'


services:
  transport-https:
    hostname: transport-https
    image: screambunn/device_transport_https
    build:
      context: ./device/transport/https
    env_file:
      - ./environment/queue.connect.env
      - ./environment/security.env
    external_links:
      - queue
    ports:
      - "5001:5001"
    depends_on:
      - queue


  transport-mqtt:
    hostname: transport-mqtt
    image: screambunn/device_transport_mqtt
    build:
      context: ./device/transport/mqtt
    env_file:
      - ./environment/queue.connect.env
      - ./environment/etcd.connect.env
      - ./environment/mqtt_transport.env
      - ./environment/security.env
    environment:
      MQTT_HOST: '91.121.93.94'  # https://test.mosquitto.org/ ** WARNING DO NOT USE IN PROD, TESTING ONLY **
    external_links:
      - etcd
      - queue
    depends_on:
      - etcd
      - queue


  actuator-base:
    hostname: actuator-base
    image: screambunn/device_actuator_base
    build:
      context: ./device/actuator/Base
    env_file:
      - ./environment/queue.connect.env
      - ./environment/etcd.connect.env
    external_links:
      - etcd
      - queue
    depends_on:
      - etcd
      - queue
    restart: on-failure


  actuator-slpf:
    hostname: actuator-slpf
    image: screambunn/device_actuator_slpf
    build:
      context: ./device/actuator/SLPF
    env_file:
      - ./environment/queue.connect.env
      - ./environment/etcd.connect.env
    external_links:
      - etcd
      - queue
    depends_on:
      - etcd
      - queue
    restart: on-failure


  queue:
    hostname: rabbit
    image: rabbitmq:management-alpine
    command: sh -c "rabbitmq-plugins enable rabbitmq_mqtt; docker-entrypoint.sh rabbitmq-server"
    volumes:
      - queue:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:15672']
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure


  etcd:
    hostname: etcd
    image: quay.io/coreos/etcd:v3.3.25
    environment:
      ALLOW_NONE_AUTHENTICATION: 'yes'
      ETCD_DATA_DIR: '/data/etcd'
    volumes:
      - etcd:/data/etcd
    command: sh -c 'etcd -listen-client-urls http://0.0.0.0:2379 -advertise-client-urls http://etcd:2379'
    restart: on-failure